name: Build
run-name: Making a production build of ${{ github.actor }}'s deployment
on: [pull_request]
jobs:
    Run-Build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v4
            - name: Setup nodejs
              uses: actions/setup-node@v4
              with:
                node-version: 22
            - name: Install dependencies
              run: npm i
            - name: Run build
              run: npm run build