name: Build
run-name: Running test build on ${{ github.actor }}'s deployment
on:
  push:
    branches:
      - master
  pull_request:

jobs:
    Run-Build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
            - name: Setup nodejs
              uses: actions/setup-node@v4
              with:
                node-version: 22
            - name: Install dependencies
              run: npm i
            - name: Add node env
              run: node -e 'process.env.CONTAINERID = "${{ secrets.CONTAINERID }}"'
            - name: Add node env 3
              run: node -e 'process.env.DBKEY = "${{secrets.DBKEY}}"'
            - name: Add node env 4
              run: node -e 'process.env.DBID = "${{ secrets.DBID }}"'
            - name: Add node env 2
              run: node -e 'process.env.DBENDPINT = "${{ secrets.DBENDPOINT }}"'
            - name: Build site
              run: npm run build
