name: Build
run-name: Running test build on ${{ github.actor }}'s deployment
on:
  push:
    branches:
      - master
  pull_request:

jobs:
    Run-Build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
            - name: Setup nodejs
              uses: actions/setup-node@v4
              with:
                node-version: 22
            - name: Install dependencies
              run: npm i
            - name: Rm files that fail to build
              run: rm src/app/unsubscribe/route.js
            - name: Rm files that fail to build
              run: rm src/app/api/writeEmail/route.js
            - name: Build site
              run: npm run build
