name: Linter style check
run-name: Checking best practices on ${{ github.actor }}'s deployment
on: [pull_request]
jobs:
    Run-Style-Check:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
            - name: Setup nodejs
              uses: actions/setup-node@v4
              with:
                node-version: 22
            - run: npm i
            - run: echo "$(npm run lint)" >> $GITHUB_OUTPUT
            - name: Fail if lint errors
              if: env.OUTPUT != "✔ No ESLint warnings or errors"
              run: exit 1
